# Generated by Django 5.1.7 on 2025-04-26 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_respostasrq"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="cargo",
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[("F", "Feminino"), ("M", "Masculino"), ("O", "Outro")],
                max_length=1,
                null=True,
            ),
        ),
    ]
